version: "3.2"

services:
  shopping-mate-back:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 --reload shopping_mate.wsgi:application
    container_name: shopping-mate-back
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    networks:
      - garcel-net

networks:
  garcel-net:
    external: true
