FROM python:3
ENV PYTHONUNBUFFERED=1

ARG ENVIRONMENT

ENV CODE_DIR="/code"
ENV REQUIREMENTS="requirements"
ENV REQUIREMENTS_DIR="${CODE_DIR}/${REQUIREMENTS}"
ENV REQUIREMENTS_FILE_NAME="${ENVIRONMENT}".txt

WORKDIR ${CODE_DIR}
COPY ${REQUIREMENTS}/${REQUIREMENTS_FILE_NAME} ${REQUIREMENTS_DIR}/

RUN pip install -r ${REQUIREMENTS_DIR}/${REQUIREMENTS_FILE_NAME}
COPY . ${CODE_DIR}/
