version: "3.2"

services:
  database:
    env_file: .env
    container_name: database
    image: postgres:latest
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - garcel-net

  shopping-mate-back:
    build:
      context: .
    command: gunicorn shopping_mate.wsgi:application --bind 0.0.0.0:8000
    container_name: shopping-mate-back
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - database
    networks:
      - garcel-net

networks:
  garcel-net:
