version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    machine:
      image: circleci/classic:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dockerize.
          command: >-
            sudo apt-get update &&
            sudo apt-get install -y wget &&
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz &&
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz &&
            sudo rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: create .env file
          command: |
            touch .env
            echo DEBUG=$DEBUG >> .env
            echo SECRET_KEY=$SECRET_KEY >> .env
            echo DATABASE_URL=$DATABASE_URL >> .env
      - run:
          name: build containers
          command: |
            docker-compose up --build -d
      - run:
          name: run tests with coverage
          command: |
            docker exec -it shopping-mate-back pytest
            docker exec -it shopping-mate-back coverage html

workflows:
  build_and_test:
    jobs:
      - build:
          post-steps:
            - codecov/upload
            - store_artifacts:
                path: htmlcov
