version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    machine:
      image: circleci/classic:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: create .env file
          command: |
            touch .env
            echo DEBUG=$DEBUG >> .env
            echo SECRET_KEY=$SECRET_KEY >> .env
            echo PORT=$PORT >> .env
            echo POSTGRES_DB=$POSTGRES_DB >> .env
      - run:
          name: build containers
          command: |
            docker-compose up --build -d
      - run:
          name: migrate
          command: |
            docker-compose run web python manage.py migrate
  test:
    machine:
      image: circleci/classic:latest

    working_directory: ~/repo

    steps:
      - run:
          name: run tests with coverage
          command: |
            docker exec -it shopping-mate-back pytest
            docker exec -it shopping-mate-back coverage html

      - store_artifacts:
          path: htmlcov

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          post-steps:
            - codecov/upload
