version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    machine:
      image: circleci/classic:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: create .env file
          command: |
            touch .env
            echo DEBUG=$DEBUG >> .env
            echo SECRET_KEY=$SECRET_KEY >> .env
            echo DATABASE_PORT=$DATABASE_PORT >> .env
            echo DATABASE_URL=$DATABASE_URL >> .env
            echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
      - run:
          name: build containers
          command: |
            docker-compose up --build -d
      - run:
          name: migrate
          command: |
            docker exec -it shopping-mate-back python manage.py migrate
      - run:
          name: run tests with coverage
          command: |
            docker exec -it shopping-mate-back pytest
            docker exec -it shopping-mate-back coverage html



workflows:
  build_and_test:
    jobs:
      - build:
          post-steps:
            - codecov/upload
            - store_artifacts:
                path: htmlcov
