version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    docker:
      - image: cimg/base:2021.10
      - image: cimg/postgres:14.0
        environment:
          PGHOST: localhost
          PGUSER: circleci
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_HOST_AUTH_METHOD: trust

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: create .env file
          command: |
            touch .env
            echo DEBUG=$DEBUG >> .env
            echo SECRET_KEY=$SECRET_KEY >> .env
            echo DATABASE_URL=$DATABASE_URL >> .env
      - run:
          name: build containers
          command: |
            docker-compose up --build -d
      - run:
          name: run tests with coverage
          command: |
            docker exec -it shopping-mate-back pytest
            docker exec -it shopping-mate-back coverage html

workflows:
  build_and_test:
    jobs:
      - build:
          post-steps:
            - codecov/upload
            - store_artifacts:
                path: htmlcov
