# Generated by Django 3.2.9 on 2021-12-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reversed_id_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='whether this item has been completed or not'),
        ),
    ]
